import type { Metadata } from "next";
import { headers } from 'next/headers' 
import { cookieToInitialState } from 'wagmi' 
import { Manrope } from "next/font/google";
import Header from "@/components/header";
import "@aragon/ods/index.css";
import "@/app/globals.css";
import Sidebar from "@/components/sidebar";
import AlertContainer from "@/components/alert/alert-container";
import { AlertProvider } from "@/context/Alerts";


import { config } from "@/context/Web3Modal";
import { Providers } from './providers'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const manrope = Manrope({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState( 
    config, 
    headers().get('cookie') 
  )

  return (
    <html lang="en">
      <head>
        <title>Potato</title>
        <link
          rel="apple-touch-icon"
          sizes="76x76"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
      </head>
      <body className="bg-neutral-50">
        <Providers initialState={initialState}>
        <AlertProvider>
          <main>
            <div className={manrope.className}>
                <div className="flex h-screen">
                  <Sidebar />
                  <div className="overflow-y-auto flex flex-col items-center w-full">
                    <div className="w-full md:w-4/5 lg:w-2/3 2xl:w-3/5 p-3">
                      <Header />
                      {children}
                    </div>
                  </div>
                </div>
            </div>
          </main>
          <AlertContainer />
        </AlertProvider>
        </Providers>
      </body>
    </html>
  );
}
