export const OftTokenBridgeAbi = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  {
    type: "error",
    inputs: [
      { name: "dao", internalType: "address", type: "address" },
      { name: "where", internalType: "address", type: "address" },
      { name: "who", internalType: "address", type: "address" },
      { name: "permissionId", internalType: "bytes32", type: "bytes32" },
    ],
    name: "DaoUnauthorized",
  },
  { type: "error", inputs: [], name: "InvalidDelegate" },
  { type: "error", inputs: [], name: "InvalidEndpointCall" },
  { type: "error", inputs: [], name: "InvalidLocalDecimals" },
  {
    type: "error",
    inputs: [{ name: "options", internalType: "bytes", type: "bytes" }],
    name: "InvalidOptions",
  },
  { type: "error", inputs: [], name: "LzTokenUnavailable" },
  {
    type: "error",
    inputs: [{ name: "eid", internalType: "uint32", type: "uint32" }],
    name: "NoPeer",
  },
  {
    type: "error",
    inputs: [{ name: "msgValue", internalType: "uint256", type: "uint256" }],
    name: "NotEnoughNative",
  },
  {
    type: "error",
    inputs: [{ name: "addr", internalType: "address", type: "address" }],
    name: "OnlyEndpoint",
  },
  {
    type: "error",
    inputs: [
      { name: "eid", internalType: "uint32", type: "uint32" },
      { name: "sender", internalType: "bytes32", type: "bytes32" },
    ],
    name: "OnlyPeer",
  },
  { type: "error", inputs: [], name: "OnlySelf" },
  {
    type: "error",
    inputs: [{ name: "result", internalType: "bytes", type: "bytes" }],
    name: "SimulationResult",
  },
  {
    type: "error",
    inputs: [
      { name: "amountLD", internalType: "uint256", type: "uint256" },
      { name: "minAmountLD", internalType: "uint256", type: "uint256" },
    ],
    name: "SlippageExceeded",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "previousAdmin",
        internalType: "address",
        type: "address",
        indexed: false,
      },
      {
        name: "newAdmin",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "AdminChanged",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "beacon",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "BeaconUpgraded",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "_enforcedOptions",
        internalType: "struct EnforcedOptionParam[]",
        type: "tuple[]",
        components: [
          { name: "eid", internalType: "uint32", type: "uint32" },
          { name: "msgType", internalType: "uint16", type: "uint16" },
          { name: "options", internalType: "bytes", type: "bytes" },
        ],
        indexed: false,
      },
    ],
    name: "EnforcedOptionSet",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [{ name: "version", internalType: "uint8", type: "uint8", indexed: false }],
    name: "Initialized",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "inspector",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "MsgInspectorSet",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "guid", internalType: "bytes32", type: "bytes32", indexed: true },
      {
        name: "srcEid",
        internalType: "uint32",
        type: "uint32",
        indexed: false,
      },
      {
        name: "toAddress",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amountReceivedLD",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "OFTReceived",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "guid", internalType: "bytes32", type: "bytes32", indexed: true },
      {
        name: "dstEid",
        internalType: "uint32",
        type: "uint32",
        indexed: false,
      },
      {
        name: "fromAddress",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amountSentLD",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "amountReceivedLD",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "OFTSent",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "eid", internalType: "uint32", type: "uint32", indexed: false },
      {
        name: "peer",
        internalType: "bytes32",
        type: "bytes32",
        indexed: false,
      },
    ],
    name: "PeerSet",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "preCrimeAddress",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "PreCrimeSet",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "implementation",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "Upgraded",
  },
  {
    type: "function",
    inputs: [],
    name: "OAPP_ADMINISTRATOR_ID",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "SEND",
    outputs: [{ name: "", internalType: "uint16", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "SEND_AND_CALL",
    outputs: [{ name: "", internalType: "uint16", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      {
        name: "origin",
        internalType: "struct Origin",
        type: "tuple",
        components: [
          { name: "srcEid", internalType: "uint32", type: "uint32" },
          { name: "sender", internalType: "bytes32", type: "bytes32" },
          { name: "nonce", internalType: "uint64", type: "uint64" },
        ],
      },
    ],
    name: "allowInitializePath",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "approvalRequired",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    inputs: [
      { name: "_eid", internalType: "uint32", type: "uint32" },
      { name: "_msgType", internalType: "uint16", type: "uint16" },
      { name: "_extraOptions", internalType: "bytes", type: "bytes" },
    ],
    name: "combineOptions",
    outputs: [{ name: "", internalType: "bytes", type: "bytes" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "composeMsgSender",
    outputs: [{ name: "sender", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "dao",
    outputs: [{ name: "", internalType: "contract IDAO", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "decimalConversionRate",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "endpoint",
    outputs: [
      {
        name: "",
        internalType: "contract ILayerZeroEndpointV2",
        type: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "uint32", type: "uint32" },
      { name: "", internalType: "uint16", type: "uint16" },
    ],
    name: "enforcedOptions",
    outputs: [{ name: "", internalType: "bytes", type: "bytes" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "implementation",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_lzEndpoint", internalType: "address", type: "address" },
      { name: "_dao", internalType: "address", type: "address" },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_eid", internalType: "uint32", type: "uint32" },
      { name: "_peer", internalType: "bytes32", type: "bytes32" },
    ],
    name: "isPeer",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      {
        name: "_origin",
        internalType: "struct Origin",
        type: "tuple",
        components: [
          { name: "srcEid", internalType: "uint32", type: "uint32" },
          { name: "sender", internalType: "bytes32", type: "bytes32" },
          { name: "nonce", internalType: "uint64", type: "uint64" },
        ],
      },
      { name: "_guid", internalType: "bytes32", type: "bytes32" },
      { name: "_message", internalType: "bytes", type: "bytes" },
      { name: "_executor", internalType: "address", type: "address" },
      { name: "_extraData", internalType: "bytes", type: "bytes" },
    ],
    name: "lzReceive",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [
      {
        name: "_packets",
        internalType: "struct InboundPacket[]",
        type: "tuple[]",
        components: [
          {
            name: "origin",
            internalType: "struct Origin",
            type: "tuple",
            components: [
              { name: "srcEid", internalType: "uint32", type: "uint32" },
              { name: "sender", internalType: "bytes32", type: "bytes32" },
              { name: "nonce", internalType: "uint64", type: "uint64" },
            ],
          },
          { name: "dstEid", internalType: "uint32", type: "uint32" },
          { name: "receiver", internalType: "address", type: "address" },
          { name: "guid", internalType: "bytes32", type: "bytes32" },
          { name: "value", internalType: "uint256", type: "uint256" },
          { name: "executor", internalType: "address", type: "address" },
          { name: "message", internalType: "bytes", type: "bytes" },
          { name: "extraData", internalType: "bytes", type: "bytes" },
        ],
      },
    ],
    name: "lzReceiveAndRevert",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [
      {
        name: "_origin",
        internalType: "struct Origin",
        type: "tuple",
        components: [
          { name: "srcEid", internalType: "uint32", type: "uint32" },
          { name: "sender", internalType: "bytes32", type: "bytes32" },
          { name: "nonce", internalType: "uint64", type: "uint64" },
        ],
      },
      { name: "_guid", internalType: "bytes32", type: "bytes32" },
      { name: "_message", internalType: "bytes", type: "bytes" },
      { name: "_executor", internalType: "address", type: "address" },
      { name: "_extraData", internalType: "bytes", type: "bytes" },
    ],
    name: "lzReceiveSimulate",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [],
    name: "msgInspector",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "uint32", type: "uint32" },
      { name: "", internalType: "bytes32", type: "bytes32" },
    ],
    name: "nextNonce",
    outputs: [{ name: "nonce", internalType: "uint64", type: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "oApp",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "oAppVersion",
    outputs: [
      { name: "senderVersion", internalType: "uint64", type: "uint64" },
      { name: "receiverVersion", internalType: "uint64", type: "uint64" },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    inputs: [],
    name: "oftVersion",
    outputs: [
      { name: "interfaceId", internalType: "bytes4", type: "bytes4" },
      { name: "version", internalType: "uint64", type: "uint64" },
    ],
    stateMutability: "pure",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "uint32", type: "uint32" }],
    name: "peers",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "preCrime",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_amountLD", internalType: "uint256", type: "uint256" }],
    name: "previewRemoveDust",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "proxiableUUID",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      {
        name: "_sendParam",
        internalType: "struct SendParam",
        type: "tuple",
        components: [
          { name: "dstEid", internalType: "uint32", type: "uint32" },
          { name: "to", internalType: "bytes32", type: "bytes32" },
          { name: "amountLD", internalType: "uint256", type: "uint256" },
          { name: "minAmountLD", internalType: "uint256", type: "uint256" },
          { name: "extraOptions", internalType: "bytes", type: "bytes" },
          { name: "composeMsg", internalType: "bytes", type: "bytes" },
          { name: "oftCmd", internalType: "bytes", type: "bytes" },
        ],
      },
    ],
    name: "quoteOFT",
    outputs: [
      {
        name: "oftLimit",
        internalType: "struct OFTLimit",
        type: "tuple",
        components: [
          { name: "minAmountLD", internalType: "uint256", type: "uint256" },
          { name: "maxAmountLD", internalType: "uint256", type: "uint256" },
        ],
      },
      {
        name: "oftFeeDetails",
        internalType: "struct OFTFeeDetail[]",
        type: "tuple[]",
        components: [
          { name: "feeAmountLD", internalType: "int256", type: "int256" },
          { name: "description", internalType: "string", type: "string" },
        ],
      },
      {
        name: "oftReceipt",
        internalType: "struct OFTReceipt",
        type: "tuple",
        components: [
          { name: "amountSentLD", internalType: "uint256", type: "uint256" },
          {
            name: "amountReceivedLD",
            internalType: "uint256",
            type: "uint256",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      {
        name: "_sendParam",
        internalType: "struct SendParam",
        type: "tuple",
        components: [
          { name: "dstEid", internalType: "uint32", type: "uint32" },
          { name: "to", internalType: "bytes32", type: "bytes32" },
          { name: "amountLD", internalType: "uint256", type: "uint256" },
          { name: "minAmountLD", internalType: "uint256", type: "uint256" },
          { name: "extraOptions", internalType: "bytes", type: "bytes" },
          { name: "composeMsg", internalType: "bytes", type: "bytes" },
          { name: "oftCmd", internalType: "bytes", type: "bytes" },
        ],
      },
      { name: "_payInLzToken", internalType: "bool", type: "bool" },
    ],
    name: "quoteSend",
    outputs: [
      {
        name: "msgFee",
        internalType: "struct MessagingFee",
        type: "tuple",
        components: [
          { name: "nativeFee", internalType: "uint256", type: "uint256" },
          { name: "lzTokenFee", internalType: "uint256", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      {
        name: "_sendParam",
        internalType: "struct SendParam",
        type: "tuple",
        components: [
          { name: "dstEid", internalType: "uint32", type: "uint32" },
          { name: "to", internalType: "bytes32", type: "bytes32" },
          { name: "amountLD", internalType: "uint256", type: "uint256" },
          { name: "minAmountLD", internalType: "uint256", type: "uint256" },
          { name: "extraOptions", internalType: "bytes", type: "bytes" },
          { name: "composeMsg", internalType: "bytes", type: "bytes" },
          { name: "oftCmd", internalType: "bytes", type: "bytes" },
        ],
      },
      {
        name: "_fee",
        internalType: "struct MessagingFee",
        type: "tuple",
        components: [
          { name: "nativeFee", internalType: "uint256", type: "uint256" },
          { name: "lzTokenFee", internalType: "uint256", type: "uint256" },
        ],
      },
      { name: "_refundAddress", internalType: "address", type: "address" },
    ],
    name: "send",
    outputs: [
      {
        name: "msgReceipt",
        internalType: "struct MessagingReceipt",
        type: "tuple",
        components: [
          { name: "guid", internalType: "bytes32", type: "bytes32" },
          { name: "nonce", internalType: "uint64", type: "uint64" },
          {
            name: "fee",
            internalType: "struct MessagingFee",
            type: "tuple",
            components: [
              { name: "nativeFee", internalType: "uint256", type: "uint256" },
              { name: "lzTokenFee", internalType: "uint256", type: "uint256" },
            ],
          },
        ],
      },
      {
        name: "oftReceipt",
        internalType: "struct OFTReceipt",
        type: "tuple",
        components: [
          { name: "amountSentLD", internalType: "uint256", type: "uint256" },
          {
            name: "amountReceivedLD",
            internalType: "uint256",
            type: "uint256",
          },
        ],
      },
    ],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [{ name: "_delegate", internalType: "address", type: "address" }],
    name: "setDelegate",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      {
        name: "_enforcedOptions",
        internalType: "struct EnforcedOptionParam[]",
        type: "tuple[]",
        components: [
          { name: "eid", internalType: "uint32", type: "uint32" },
          { name: "msgType", internalType: "uint16", type: "uint16" },
          { name: "options", internalType: "bytes", type: "bytes" },
        ],
      },
    ],
    name: "setEnforcedOptions",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_msgInspector", internalType: "address", type: "address" }],
    name: "setMsgInspector",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_eid", internalType: "uint32", type: "uint32" },
      { name: "_peer", internalType: "bytes32", type: "bytes32" },
    ],
    name: "setPeer",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_preCrime", internalType: "address", type: "address" }],
    name: "setPreCrime",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "sharedDecimals",
    outputs: [{ name: "", internalType: "uint8", type: "uint8" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    inputs: [],
    name: "token",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "newImplementation", internalType: "address", type: "address" }],
    name: "upgradeTo",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "newImplementation", internalType: "address", type: "address" },
      { name: "data", internalType: "bytes", type: "bytes" },
    ],
    name: "upgradeToAndCall",
    outputs: [],
    stateMutability: "payable",
  },
] as const;
