export const ToucanRelayAbi = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  {
    inputs: [
      { internalType: "uint256", name: "proposalRef", type: "uint256" },
      { internalType: "enum ToucanRelay.ErrReason", name: "reason", type: "uint8" },
    ],
    name: "CannotDispatch",
    type: "error",
  },
  { inputs: [], name: "CannotReceive", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "proposalRef", type: "uint256" },
      { internalType: "address", name: "voter", type: "address" },
      {
        components: [
          { internalType: "uint256", name: "abstain", type: "uint256" },
          { internalType: "uint256", name: "yes", type: "uint256" },
          { internalType: "uint256", name: "no", type: "uint256" },
        ],
        internalType: "struct IVoteContainer.Tally",
        name: "voteOptions",
        type: "tuple",
      },
      { internalType: "enum ToucanRelay.ErrReason", name: "reason", type: "uint8" },
    ],
    name: "CannotVote",
    type: "error",
  },
  {
    inputs: [
      { internalType: "address", name: "dao", type: "address" },
      { internalType: "address", name: "where", type: "address" },
      { internalType: "address", name: "who", type: "address" },
      { internalType: "bytes32", name: "permissionId", type: "bytes32" },
    ],
    name: "DaoUnauthorized",
    type: "error",
  },
  { inputs: [], name: "InvalidDelegate", type: "error" },
  { inputs: [], name: "InvalidDestinationEid", type: "error" },
  { inputs: [], name: "InvalidEndpointCall", type: "error" },
  {
    inputs: [{ internalType: "uint16", name: "optionType", type: "uint16" }],
    name: "InvalidOptionType",
    type: "error",
  },
  { inputs: [], name: "InvalidToken", type: "error" },
  { inputs: [], name: "LzTokenUnavailable", type: "error" },
  { inputs: [{ internalType: "uint32", name: "eid", type: "uint32" }], name: "NoPeer", type: "error" },
  { inputs: [{ internalType: "uint256", name: "msgValue", type: "uint256" }], name: "NotEnoughNative", type: "error" },
  { inputs: [{ internalType: "address", name: "addr", type: "address" }], name: "OnlyEndpoint", type: "error" },
  {
    inputs: [
      { internalType: "uint32", name: "eid", type: "uint32" },
      { internalType: "bytes32", name: "sender", type: "bytes32" },
    ],
    name: "OnlyPeer",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "address", name: "previousAdmin", type: "address" },
      { indexed: false, internalType: "address", name: "newAdmin", type: "address" },
    ],
    name: "AdminChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "beacon", type: "address" }],
    name: "BeaconUpgraded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "uint32", name: "buffer", type: "uint32" }],
    name: "BrigeDelayBufferUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "uint32", name: "dstEid", type: "uint32" }],
    name: "DestinationEidUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "uint8", name: "version", type: "uint8" }],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint32", name: "eid", type: "uint32" },
      { indexed: false, internalType: "bytes32", name: "peer", type: "bytes32" },
    ],
    name: "PeerSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "implementation", type: "address" }],
    name: "Upgraded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint32", name: "dstEid", type: "uint32" },
      { indexed: true, internalType: "uint256", name: "proposalRef", type: "uint256" },
      { indexed: false, internalType: "address", name: "voter", type: "address" },
      {
        components: [
          { internalType: "uint256", name: "abstain", type: "uint256" },
          { internalType: "uint256", name: "yes", type: "uint256" },
          { internalType: "uint256", name: "no", type: "uint256" },
        ],
        indexed: false,
        internalType: "struct IVoteContainer.Tally",
        name: "voteOptions",
        type: "tuple",
      },
    ],
    name: "VoteCast",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint32", name: "dstEid", type: "uint32" },
      { indexed: true, internalType: "uint256", name: "proposalRef", type: "uint256" },
      {
        components: [
          { internalType: "uint256", name: "abstain", type: "uint256" },
          { internalType: "uint256", name: "yes", type: "uint256" },
          { internalType: "uint256", name: "no", type: "uint256" },
        ],
        indexed: false,
        internalType: "struct IVoteContainer.Tally",
        name: "votes",
        type: "tuple",
      },
    ],
    name: "VotesDispatched",
    type: "event",
  },
  {
    inputs: [],
    name: "OAPP_ADMINISTRATOR_ID",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "UPGRADE_PLUGIN_PERMISSION_ID",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "uint32", name: "srcEid", type: "uint32" },
          { internalType: "bytes32", name: "sender", type: "bytes32" },
          { internalType: "uint64", name: "nonce", type: "uint64" },
        ],
        internalType: "struct Origin",
        name: "origin",
        type: "tuple",
      },
    ],
    name: "allowInitializePath",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "buffer",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_proposalRef", type: "uint256" }],
    name: "canDispatch",
    outputs: [
      { internalType: "bool", name: "", type: "bool" },
      { internalType: "enum ToucanRelay.ErrReason", name: "", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_proposalRef", type: "uint256" },
      { internalType: "address", name: "_voter", type: "address" },
      {
        components: [
          { internalType: "uint256", name: "abstain", type: "uint256" },
          { internalType: "uint256", name: "yes", type: "uint256" },
          { internalType: "uint256", name: "no", type: "uint256" },
        ],
        internalType: "struct IVoteContainer.Tally",
        name: "_voteOptions",
        type: "tuple",
      },
    ],
    name: "canVote",
    outputs: [
      { internalType: "bool", name: "", type: "bool" },
      { internalType: "enum ToucanRelay.ErrReason", name: "", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "composeMsgSender",
    outputs: [{ internalType: "address", name: "sender", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "dao",
    outputs: [{ internalType: "contract IDAO", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_proposalRef", type: "uint256" },
      {
        components: [
          { internalType: "uint128", name: "gasLimit", type: "uint128" },
          {
            components: [
              { internalType: "uint256", name: "nativeFee", type: "uint256" },
              { internalType: "uint256", name: "lzTokenFee", type: "uint256" },
            ],
            internalType: "struct MessagingFee",
            name: "fee",
            type: "tuple",
          },
          { internalType: "bytes", name: "options", type: "bytes" },
        ],
        internalType: "struct ToucanRelay.LzSendParams",
        name: "_params",
        type: "tuple",
      },
    ],
    name: "dispatchVotes",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "dstEid",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "endpoint",
    outputs: [{ internalType: "contract ILayerZeroEndpointV2", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint32", name: "_dstEid", type: "uint32" },
      { internalType: "uint256", name: "_proposalRef", type: "uint256" },
      { internalType: "address", name: "_voter", type: "address" },
    ],
    name: "getVotes",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "abstain", type: "uint256" },
          { internalType: "uint256", name: "yes", type: "uint256" },
          { internalType: "uint256", name: "no", type: "uint256" },
        ],
        internalType: "struct IVoteContainer.Tally",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_proposalRef", type: "uint256" },
      { internalType: "address", name: "_voter", type: "address" },
    ],
    name: "getVotes",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "abstain", type: "uint256" },
          { internalType: "uint256", name: "yes", type: "uint256" },
          { internalType: "uint256", name: "no", type: "uint256" },
        ],
        internalType: "struct IVoteContainer.Tally",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_proposalRef", type: "uint256" }],
    name: "hasEnoughTimeToBridge",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "implementation",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_token", type: "address" },
      { internalType: "address", name: "_lzEndpoint", type: "address" },
      { internalType: "address", name: "_dao", type: "address" },
      { internalType: "uint32", name: "_dstEid", type: "uint32" },
      { internalType: "uint32", name: "_buffer", type: "uint32" },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_proposalRef", type: "uint256" }],
    name: "isProposalOpen",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "uint32", name: "srcEid", type: "uint32" },
          { internalType: "bytes32", name: "sender", type: "bytes32" },
          { internalType: "uint64", name: "nonce", type: "uint64" },
        ],
        internalType: "struct Origin",
        name: "_origin",
        type: "tuple",
      },
      { internalType: "bytes32", name: "_guid", type: "bytes32" },
      { internalType: "bytes", name: "_message", type: "bytes" },
      { internalType: "address", name: "_executor", type: "address" },
      { internalType: "bytes", name: "_extraData", type: "bytes" },
    ],
    name: "lzReceive",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint32", name: "", type: "uint32" },
      { internalType: "bytes32", name: "", type: "bytes32" },
    ],
    name: "nextNonce",
    outputs: [{ internalType: "uint64", name: "nonce", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "oAppVersion",
    outputs: [
      { internalType: "uint64", name: "senderVersion", type: "uint64" },
      { internalType: "uint64", name: "receiverVersion", type: "uint64" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    name: "peers",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pluginType",
    outputs: [{ internalType: "enum IPlugin.PluginType", name: "", type: "uint8" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_proposalRef", type: "uint256" }],
    name: "proposals",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "abstain", type: "uint256" },
          { internalType: "uint256", name: "yes", type: "uint256" },
          { internalType: "uint256", name: "no", type: "uint256" },
        ],
        internalType: "struct IVoteContainer.Tally",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint32", name: "_dstEid", type: "uint32" },
      { internalType: "uint256", name: "_proposalRef", type: "uint256" },
    ],
    name: "proposals",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "abstain", type: "uint256" },
          { internalType: "uint256", name: "yes", type: "uint256" },
          { internalType: "uint256", name: "no", type: "uint256" },
        ],
        internalType: "struct IVoteContainer.Tally",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "proxiableUUID",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_proposalRef", type: "uint256" },
      { internalType: "uint128", name: "_gasLimit", type: "uint128" },
    ],
    name: "quote",
    outputs: [
      {
        components: [
          { internalType: "uint128", name: "gasLimit", type: "uint128" },
          {
            components: [
              { internalType: "uint256", name: "nativeFee", type: "uint256" },
              { internalType: "uint256", name: "lzTokenFee", type: "uint256" },
            ],
            internalType: "struct MessagingFee",
            name: "fee",
            type: "tuple",
          },
          { internalType: "bytes", name: "options", type: "bytes" },
        ],
        internalType: "struct ToucanRelay.LzSendParams",
        name: "params",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_dstEid", type: "uint256" }],
    name: "refundAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32", name: "_buffer", type: "uint32" }],
    name: "setBridgeDelayBuffer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_delegate", type: "address" }],
    name: "setDelegate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32", name: "_dstEid", type: "uint32" }],
    name: "setDstEid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint32", name: "_eid", type: "uint32" },
      { internalType: "bytes32", name: "_peer", type: "bytes32" },
    ],
    name: "setPeer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "_interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token",
    outputs: [{ internalType: "contract IVotes", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newImplementation", type: "address" }],
    name: "upgradeTo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "newImplementation", type: "address" },
      { internalType: "bytes", name: "data", type: "bytes" },
    ],
    name: "upgradeToAndCall",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_proposalRef", type: "uint256" },
      {
        components: [
          { internalType: "uint256", name: "abstain", type: "uint256" },
          { internalType: "uint256", name: "yes", type: "uint256" },
          { internalType: "uint256", name: "no", type: "uint256" },
        ],
        internalType: "struct IVoteContainer.Tally",
        name: "_voteOptions",
        type: "tuple",
      },
    ],
    name: "vote",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
